<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="4-hamlet.css"?>

<!DOCTYPE play [
    <!ELEMENT play (author,title, acts)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT acts (act+)>
    <!ELEMENT act (number, title, scenes)>
    <!ELEMENT number (#PCDATA)>
    <!ELEMENT scenes (scene+)>
    <!ELEMENT scene (number, title, content)>
    <!ELEMENT content ((dialogue | instruction)*)>
    <!ELEMENT dialogue (source, (line*| instruction)*)>
    <!ELEMENT source (#PCDATA)>
    <!ELEMENT line (#PCDATA)>
    <!ELEMENT instruction (text)>
    <!ATTLIST instruction t (ownline|inline) "ownline">
    <!ELEMENT text (#PCDATA)>
]>

<play>
    <author>
        William Shakespeare
    </author>
    <title>
        The Tragedy of Hamlet, Prince of Denmark
    </title>
    <acts>
        <act>
            <number> 1 </number>
            <title>ACT I</title>
            <scenes>
                <scene>
                    <number> 5 </number>
                    <title>SCENE V. Another part of the platform.</title>
                    <content>
                        <dialogue>
                            <source>HAMLET</source>
                            <line>O all you host of heaven! O earth! What else?
                            </line>
                            <line>And shall I couple hell? O, fie! Hold, hold, my heart;
                            </line>
                            <line>And you, my sinews, grow not instant old,
                            </line>
                            <line>But bear me stiffly up. Remember thee!
                            </line>
                            <line>Ay, thou poor ghost, while memory holds a seat
                            </line>
                            <line>In this distracted globe. Remember thee!
                            </line>
                            <line>Yea, from the table of my memory
                            </line>
                            <line>I'll wipe away all trivial fond records,
                            </line>
                            <line>All saws of books, all forms, all pressures past,
                            </line>
                            <line>That youth and observation copied there;
                            </line>
                            <line>And thy commandment all alone shall live
                            </line>
                            <line>Within the book and volume of my brain,
                            </line>
                            <line>Unmix'd with baser matter: yes, by heaven!
                            </line>
                            <line>O most pernicious woman!
                            </line>
                            <line>O villain, villain, smiling, damned villain!
                            </line>
                            <line>My tables,--meet it is I set it down,
                            </line>
                            <line>That one may smile, and smile, and be a villain;
                            </line>
                            <line>At least I'm sure it may be so in Denmark:
                            </line>
                            <instruction t="ownline">
                                <text>[Writing]</text>
                            </instruction>
                            <line>So, uncle, there you are. Now to my word;
                            </line>
                            <line>It is 'Adieu, adieu! remember me.'
                            </line>
                            <line>I have sworn 't.</line>
                        </dialogue>

                        <instruction t="ownline">
                            <text>[Enter HORATIO and MARCELLUS]</text>
                        </instruction>

                        <dialogue>
                            <source>HORATIO</source>
                            <instruction t="inline">
                                <text>[Within]</text>
                            </instruction>
                            <line> My lord, my lord,--</line>
                        </dialogue>

                        <dialogue>
                            <source>MARCELLUS</source>
                            <instruction t="inline">
                                <text>[Within]</text>
                            </instruction>
                            <line>  Lord Hamlet,--</line>
                        </dialogue>

                        <dialogue>
                            <source>HORATIO</source>
                            <instruction t="inline">
                                <text>[Within]</text>
                            </instruction>
                            <line> Heaven secure him!</line>
                        </dialogue>

                        <dialogue>
                            <source>HAMLET</source>
                            <line>So be it!</line>
                        </dialogue>

                        <dialogue>
                            <source>HORATIO</source>
                            <instruction t="inline">
                                <text>[Within]</text>
                            </instruction>
                            <line> Hillo, ho, ho, my lord!</line>
                        </dialogue>

                        <dialogue>
                            <source>HAMLET</source>
                            <line>Hillo, ho, ho, boy! come, bird, come.</line>
                        </dialogue>

                    </content>
                </scene>
            </scenes>
        </act>
    </acts>
</play>
